### ISSUE TITLE
Hello, you are doing a great job. I have a few questions and I hope to get your answers.

### ISSUE THREAD

**Issue by GhYang0519** [Kaiseem/QueryOTR#1]
1.Do you intend to open source your model ？
2.According to the data set you mentioned, how long has your model been trained, and on what equipment?
3.How well does this method work for larger images? Such as 1920 ✖ ️ 1080
4.What is the speed of reasoning? On what device ?
If you can answer, I will be very grateful! Thanks.

**Comment by GhYang0519** [comment]
I see that GeForceRTX3090 is mentioned in your paper, but it seems that the specific training time is not specified.

**Comment by Kaiseem** [comment]
HI, for your questions:

1. We have test the public code, and directly train the code can reach our reported results (even higher with different seed).
2. It cost about one day on one computer equiped with Intel 10850K and RTX 3090
3. We didn't investigate in larger images. In my opinion, if train the model on larger datasets (e.g., OpenImage) and larger image size, it could. However, it would cost tons of computation resource.
4. Very fast. According to our supplementary material, it cost 13 ms/image

**Comment by GhYang0519** [comment]
哥，🐮🍺

**Comment by GhYang0519** [comment]
我准备复现您的方法，请问：
1.您是对您提到的三个数据集合并到一起作为您的训练集和验证集吗？
2.我是否可制定只在横向外绘，也就是说将竖版外绘成横版。

**Comment by Kaiseem** [comment]
1. 并不是，是分别在三个数据集上训练，且分别在各自的验证机上测试
2. 可以，你可以修改代码以适配你的任务

**Comment by GhYang0519** [comment]
你好，我想针对您提供的建筑数据集进行复现，我想将数据直接下载到linux服务器上，但我看到数据集是百度网盘的连接，请问有数据集的原始链接嘛？

**Comment by Kaiseem** [comment]
不好意思，好像没有，building这个数据集是我们同事收集的

**Comment by angeleyeKJ** [comment]
> 你好，我想针对您提供的建筑数据集进行复现，我想将数据直接下载到linux服务器上，但我看到数据集是百度网盘的连接，请问有数据集的原始链接嘛？

https://github.com/houtianze/bypy
你值得拥有~
