### ISSUE TITLE
结果网格化严重

### ISSUE THREAD

**Issue by Kuekua** [Kaiseem/QueryOTR#2]
你好！感谢你的分享！
我在尝试迁移你的工作到我的任务中，我想输入512x512的图片，然后让网络生成左边，输出512x1024的图片，只改了输入输出大小，但是结果比较差，对于复杂背景有网格现象，简单背景有的patch像素异常，如下图（左边原图，右边生成图，输入是原图的右半边），可能的原因是什么呢？是否需要改变patch的大小？
![184_1663306838 958556](https://user-images.githubusercontent.com/26383252/190579367-a813f225-b64c-464a-8052-9cecff04c4fe.png)

**Comment by Kuekua** [comment]
> 你好，这是有可能的，由于实验setting有比较大的不一样，我有以下一些建议：1. 确保测试时候的position embedding在训练的时候都见过， 2. 你可以尝试多步少量的外扩，比如训练的时候只训练512-》640，然后inference的时候，多次inference，这样可以减小训练难度，3. 如果训练的时候很难收敛，尝试增加训练时间\样本数量，或者换一个backbone（如swim之类的）来加速收敛

**Comment by Kuekua** [comment]
感谢回复！
1. 训练和测试都是只让网络生成左半边，所以position embedding应该不是问题
2. 多次外扩是个很好的点子，我看你论文也有提到，是否在训练时也要这样做，因为生成的内容和原内容分布是不是会不一样
3. 我这边已经把原先的VIT_base_patch16更好为更大的VIT_large_patch32，貌似有缓解

**Comment by Kaiseem** [comment]
wish everything is ok
