### ISSUE TITLE
实验结果与论文相差很大

### ISSUE THREAD

**Issue by Jdl123456** [Kaiseem/QueryOTR#4]
![image](https://user-images.githubusercontent.com/83056773/194879215-1b3b5e7b-db00-4e10-bff4-bcff0b30e761.png)
您好，在基本未对代码进行修改的情况下，我复现出来实验结果很差，FID指标和IS指标，但不知道什么问题，还希望您有空指点迷津

**Comment by PengleiGao** [comment]
![1665464574367](https://user-images.githubusercontent.com/48986008/195001284-f9a04bf5-a49c-4e8c-a455-61c36d5855ef.png)
这个问题估计是你测试的时候torchvision的版本问题，导致weight读不出来。这里weight=None了。
建议升级一下版本再看看。
我们本地测试是没有问题的，我们的torchvision版本是0.8。

**Comment by Jdl123456** [comment]
好的，我试一下，非常感谢您的解答！

**Comment by PengleiGao** [comment]
你也再看一下生成的图片质量如何，如果fid真的是106那图片质量应该会挺差，如果图片比较差那就有可能模型跑的不太对

**Comment by Jdl123456** [comment]
好的前辈，我跑的时候参数和您在源代码设置的参数基本一致，只是使用了自己的数据集，按道理应该跑出来效果没这么差。另外我想问一下，测试集产生了两个文件夹generated的gt，这个gt（也就是192*192的ground truth图像）是模型自动生成的吗，又是依据什么生成的呢，这里没太懂矣。非常感谢您的耐心解答！

**Comment by Kaiseem** [comment]
你好, gt的图是直接resize测试集的图到192*192 （ transforms.Resize），不一定适合所有setting，只是一个固定的setting针对实验，所以要确定直接resize图片是否对你的测试集合理（比如过长的图会不合理），并且我们的代码只能确保我们给与的数据集的效果，自己数据集的话需要针对性调整一些超参数，以确保模型可以完全收敛。你可以放一些你得到的结果吗？如果不是特别差那可能是torchvision版本的问题

**Comment by Kaiseem** [comment]
另外 patch_mean和patch_std是根据scenery这个数据集算出来的，每个数据集都会计算一个这个，将图resize到192*192然后按32*32 patch_size和16*16的stride分割出patch后，计算数据集所有patch的mean的平均和std的平均作为patch_mean和patch_std

**Comment by Jdl123456** [comment]
谢谢前辈耐心解答~

**Comment by Kaiseem** [comment]
这里报的错是读取的checkpoint是以6层transformer decoder训练且储存的，然后读取不进4层的transformer deocder，所以transformer_decoder.4 和.5是unexpected keys。确保训练与测试的时候网络结构一致。另外为了debug，建议以下pipeline:1.先跑以下第一个数据集复现以下，确保环境没问题，2. 训练自己的数据集的时候看看中间的生成结果，然后根据数据及大小调下参数

**Comment by Jdl123456** [comment]
好的前辈，非常感谢您的建议！

**Comment by Jdl123456** [comment]
我用现有环境训练和测试了一下scenery数据集，然后结果和您的结果相差比较大，参数我基本上没有改变呢，可能还是环境没配置好
![1](https://user-images.githubusercontent.com/83056773/195241484-3004d366-043a-4535-8dca-c865e9709f85.png)

**Comment by Kaiseem** [comment]
这里是我的一些关键环境版本，python==3.7.3, torch==1.10.0+cu113, torchvision==0.11.0, mmcv==1.4.8, 建议把torchvision自动下载的checkpoint删了让它重新下载，因为代码在我们这5台不同环境的设备里跑都没有问题，所以最好排查一下

**Comment by Jdl123456** [comment]
好的前辈，我重新配置下环境试试~

**Comment by Kaiseem** [comment]
wish everything is ok

**Comment by Jdl123456** [comment]
> 这里是我的一些关键环境版本，python==3.7.3, torch==1.10.0+cu113, torchvision==0.11.0, mmcv==1.4.8, 建议把torchvision自动下载的checkpoint删了让它重新下载，因为代码在我们这5台不同环境的设备里跑都没有问题，所以最好排查一下

前辈，请问除了以上关键参数，环境还需要注意什么吗。我配了和您相同的环境，测试了一下scenery数据集，但是FID有60多矣

**Comment by Kaiseem** [comment]
你可以检查下训练过程的图和测试结果的图，排查下问题，并且是否改过代码改出了bug？

**Comment by Jdl123456** [comment]
好的，我想问一下就是从github下载代码如果不加修改进行复现的话，测试scenery的结果中FID应该接近20.366才对，我现在最好也才到44.753，感觉还是哪里出了问题

**Comment by Kaiseem** [comment]
我不知道是啥情况。。你要不拿我这个分好的风景数据集直接训练一把，不要任何预处理，解压下来直接训练

链接：https://pan.baidu.com/s/1ynCfMa_HyzVYzSTBOVssVw?pwd=xyxe 
提取码：xyxe 
--来自百度网盘超级会员V4的分享

**Comment by Jdl123456** [comment]
好滴前辈，我用了您的数据集，FID是21.0206，IS是3.7714，虽然还有点差距，但是已经改善很多了

**Comment by Jdl123456** [comment]
好滴前辈，我用了您的数据集，FID是21.0206，IS是3.7714，虽然还有点差距，但是已经改善很多了

**Comment by Kaiseem** [comment]
https://github.com/Kaiseem/QueryOTR/issues/7

**Comment by Kaiseem** [comment]
pls check the readme for the updated checkpoints on Scenery

**Comment by Jdl123456** [comment]
前辈您好，如果我想复现一下您在PSM和可变形卷积的消融实验，需要在代码的哪个模块进行修改呀，代码水平不大行我

**Comment by Kaiseem** [comment]
你好，对于PSM的消融实验，可以定义PSM的时候将参数overlap_size设置为0，就等价于一个linear了，然后对于可变卷积的消融实验，https://github.com/Kaiseem/QueryOTR/blob/50bf73f372bfb87db3fef889dbaeb16c4954eba9/models/QEM.py#L36 改成 self.conv2 =  nn.Conv2d(planes, planes, 3, 1, 1) 即可

**Comment by Jdl123456** [comment]
![image](https://user-images.githubusercontent.com/83056773/208893419-80d7ae25-fde2-4a35-a152-e9996996b8c5.png)
前辈，我在训练完成后，进行测试，遇到了这个问题，请问这是怎么回事呀

**Comment by Kaiseem** [comment]
这应该是个bug，但我没遇到过，google百度一下

**Comment by Jdl123456** [comment]
好的前辈，还想请问复现噪声的消融实验应该修改哪一行呢，感谢！

**Comment by Kaiseem** [comment]
在 https://github.com/Kaiseem/QueryOTR/blob/50bf73f372bfb87db3fef889dbaeb16c4954eba9/models/QEM.py#L52 这个class里，在__init__里定义一个新的可学习weight，self.learnable_query = nn.Embedding([self.output_query_width**2, hidden_num]), 然后在forward函数里将initial_query赋值为 self.learnable_query.weight[None,:,:]

**Comment by Jdl123456** [comment]
好的明白了，非常感谢！
请问感知函数的消融实验是不是注释掉losses/__init__.py中line32这行代码就行了：g_loss_dict['loss_g_perceptual']=self.perceptual_loss(self.renorm(input_fake),self.renorm(input_real))

**Comment by Jdl123456** [comment]
![9U 4N}M~7BH6%)LQ}1_9A5F](https://user-images.githubusercontent.com/83056773/210951714-805f8b8c-b5ae-4576-b44e-a7e501901b15.jpg)
另外按照您说的修改噪声，但是报错了矣

**Comment by Kaiseem** [comment]
你可以尝试把self.gen_weight_dict={'loss_g_recon':5, 'loss_g_adversarial':1, 'loss_g_perceptual':10} 里的'loss_g_perceptual'权重设为0 或者把g_loss_dict['loss_g_perceptual']=0，这样不容易出bug，另外embedding那个我多写了个中括号，去掉应该就行了，详情可以看看pytorch的官方document

**Comment by Jdl123456** [comment]
![9AV)}PV( DN6OPY113FZ {R](https://user-images.githubusercontent.com/83056773/211010027-fc2bcc5c-de6f-4e7b-90e4-af635330e7b8.jpg)
好的，噪声那个好像还是报错矣
