### ISSUE TITLE
您好，复现结果与论文结果有差距

### ISSUE THREAD

**Issue by brucelighter** [Kaiseem/QueryOTR#7]
scenery6000数据集采用该论文的分法，epoch设置成300.也是在3090上训练的。
FID值是21.08， 论文里是20.366
IS是3.81，论文里是3.955
上面两个值与论文结果的差距是否是正常的？

此外，我也计算了PSNR值，这一项相差较大，我测出来是21.63，原论文是23.60.
训练代码没有进行任何修改

**Comment by Kaiseem** [comment]
这是有可能的，因为在做的时候 MAE还没公开正式代码，当时用的是非官方的代码 https://github.com/pengzhiliang/MAE-pytorch ，然后现在迁移到了官方代码上，然后现在代码里可能有个地方和我原来实现不一样的是，现在代码读取weight的时候会插值pos emb

https://github.com/Kaiseem/QueryOTR/blob/729f289dedac2823efa0e926b2c3d8a7942bc528/models/VIT.py#L88

但我之前的实现没有插值，而是用了原始pos emb，然后输入的时候只输入最中间的position embeding，类似于这个实现

https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/modeling_pretrain.py#L263

因为其他地方都没改，所以我没check这个影响大不大，希望对你有帮助

**Comment by Kaiseem** [comment]
原始实现类似于这样，

https://github.com/Kaiseem/QueryOTR/blob/729f289dedac2823efa0e926b2c3d8a7942bc528/models/VITGen.py#L57

`    def forward(self, samples):
        x = samples['input']
        gt_inner = samples['gt_inner']
        b,c,w,h=x.size()
        assert w==128 and h==128
        temp_x = F.pad(x, (48, 48, 48, 48), mode='reflect')
        temp = torch.ones(size=(14, 14)).long()
        temp[3:-3, 3:-3] = 0
        temp = temp.view(-1).expand(b, -1).contiguous().bool()
        src = self.transformer_encoder.forward_features(temp_x, temp)  # b n c`

**Comment by Kaiseem** [comment]
code类似于这样

```
    def forward(self, samples):
        x = samples['input']
        gt_inner = samples['gt_inner']
        b,c,w,h=x.size()
        assert w==128 and h==128
        temp_x = F.pad(x, (48, 48, 48, 48), mode='reflect')
        temp = torch.ones(size=(14, 14)).long()
        temp[3:-3, 3:-3] = 0
        temp = temp.view(-1).expand(b, -1).contiguous().bool()
        src = self.transformer_encoder.forward_features(temp_x, temp)  # b n c
```

**Comment by brucelighter** [comment]
请问有训练好的模型参数吗

**Comment by brucelighter** [comment]
> code类似于这样
> 
> ```
>     def forward(self, samples):
>         x = samples['input']
>         gt_inner = samples['gt_inner']
>         b,c,w,h=x.size()
>         assert w==128 and h==128
>         temp_x = F.pad(x, (48, 48, 48, 48), mode='reflect')
>         temp = torch.ones(size=(14, 14)).long()
>         temp[3:-3, 3:-3] = 0
>         temp = temp.view(-1).expand(b, -1).contiguous().bool()
>         src = self.transformer_encoder.forward_features(temp_x, temp)  # b n c
> ```

请问有训练好的模型参数吗

**Comment by Kaiseem** [comment]
我会在近期de下bug，然后share训练好的参数

**Comment by brucelighter** [comment]
> 我会在近期de下bug，然后share训练好的参数

谢谢

**Comment by Kaiseem** [comment]
Please check the README for the checkpoints

**Comment by Jdl123456** [comment]
前辈您好，请问如果想要多步出图的话，只需修改测试使用的参数input_size和output_size嘛2，好像会报错矣

**Comment by Jdl123456** [comment]
前辈您好，我想问如果想要实现多步出图的吗，仅仅修改input_size和output_size会报错，请问应该怎么实现多步出图呢？谢谢！

**Comment by Kaiseem** [comment]
你好，如果想多步出图可以有两种思路：1) 不改变图像大小，但用sliding windows滑动，然后将预测的外圈拼接起来；2)改变图像的大小的情况下，多步就把128->192的图再缩成128，再扩成192，如此反复。论文里使用了后者的方法(see Sec.4.1)，是因为这样对比CNN的方法比较公平且可容易实现。具体的实现你可以自己实现一下。

**Comment by Jdl123456** [comment]
> 你好，如果想多步出图可以有两种思路：1) 不改变图像大小，但用sliding windows滑动，然后将预测的外圈拼接起来；2)改变图像的大小的情况下，多步就把128->192的图再缩成128，再扩成192，如此反复。论文里使用了后者的方法(see Sec.4.1)，是因为这样对比CNN的方法比较公平且可容易实现。具体的实现你可以自己实现一下。

好的感谢！
