### ISSUE TITLE
Problem of reproduction.

### ISSUE THREAD

**Issue by Sherrylone** [Kaiseem/QueryOTR#9]
Dear authors, thanks for your great work. 
I have a little problem reproducing the results reported in the paper. 
On the Scenery dataset, you mentioned the upper bound of IS score is 4.091, so did you only use the test set to compute the score or the whole dataset? If using test set only, how to select the test set?
 In my experiments, when I use the total dataset to compute the IS, I get 3.744, and when I use the last 1000 images to compute the IS, I get 3.541. Could you give me some advice? Thanks a lot

**Comment by Kaiseem** [comment]
Hi, you can refer to https://github.com/Kaiseem/QueryOTR/blob/50bf73f372bfb87db3fef889dbaeb16c4954eba9/evaluate.py#L79 , the code used to evaluate the IS socre in our paper. Meanwhile, the split of scenery dataset can be found here https://pan.baidu.com/s/1Zn5X3jfqr6x3ho705VMHZA?pwd=qotr

**Comment by Sherrylone** [comment]
Thanks for your clarification.

**Comment by Sherrylone** [comment]
Dear authors, could you provide the index of train/test set of the Scenery dataset? 
The downloading process is too time-consuming.

**Comment by Kaiseem** [comment]
Sure, the images' names for testing are startedfrom scenery_5041  and end to scenery_6040

**Comment by Sherrylone** [comment]
Thank you very much!
